### ISSUE TITLE
Is there a chance to support 120FPS ?

### ISSUE THREAD

**Issue by boybook** [MichaelMKenny/moonlight-macos#1]
Maybe like 2K 120fps on MacBook Pro 2021

**Comment by MichaelMKenny** [comment]
Fixed in [55151e1](https://github.com/MichaelMKenny/moonlight-macos/commit/55151e159c3fa8927e65779856553c596cbdecbf).

Note: I don't actually have one of the shiny new MacBook Pros, but I do have a 144Hz external monitor, which I set to 120Hz, and it worked fine on that. So do let me know, once I've made a release, whether or not it works for you :)

Also you'll get the best experience if you create a 120Hz custom resolution, in the Nvidia control panel, and set your desktop resolution to that resolution.
